export interface League {
  id: string;
  name: string;
  displayName: string;
  badge?: string;
}

export interface Sport {
  id: string;
  name: string;
  iconName: string; // For lucide icons, SVG filename, or PNG filename
  iconType?: 'lucide' | 'svg' | 'custom'; // Determines how to render the icon (custom = PNG)
  leagues: League[];
}

export const sportsData: Sport[] = [
  {
    id: "soccer",
    name: "Football",
    iconName: "soccer",
    iconType: "svg",
    leagues: [
      { id: "4328", name: "English Premier League", displayName: "EPL", badge: "https://r2.thesportsdb.com/images/media/league/badge/gasy9d1737743125.png" },
      { id: "4335", name: "Spanish La Liga", displayName: "La Liga", badge: "https://r2.thesportsdb.com/images/media/league/badge/ja4it51687628717.png" },
      { id: "5088", name: "Spanish Primera Federación", displayName: "Primera Fed", badge: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Primera_Federaci%C3%B3n.svg/794px-Primera_Federaci%C3%B3n.svg.png" },
      { id: "4331", name: "German Bundesliga", displayName: "Bundesliga", badge: "https://r2.thesportsdb.com/images/media/league/badge/teqh1b1679952008.png" },
      { id: "4332", name: "Italian Serie A", displayName: "Serie A", badge: "https://r2.thesportsdb.com/images/media/league/badge/67q3q21679951383.png" },
      { id: "4334", name: "French Ligue 1", displayName: "Ligue 1", badge: "https://r2.thesportsdb.com/images/media/league/badge/9f7z9d1742983155.png" },
      { id: "4337", name: "Dutch Eredivisie", displayName: "Eredivisie", badge: "https://r2.thesportsdb.com/images/media/league/badge/5cdsu21725984946.png" },
      { id: "4344", name: "Portuguese Primeira Liga", displayName: "Primeira Liga", badge: "https://r2.thesportsdb.com/images/media/league/badge/lkfko71751917970.png" },
      { id: "4339", name: "Turkish Super Lig", displayName: "Super Lig", badge: "https://r2.thesportsdb.com/images/media/league/badge/h7xx231601671132.png" },
      { id: "4330", name: "Scottish Premiership", displayName: "Scottish Prem", badge: "https://r2.thesportsdb.com/images/media/league/badge/72d3zc1688333496.png" },
      { id: "4621", name: "Austrian Bundesliga", displayName: "Austrian BL", badge: "https://r2.thesportsdb.com/images/media/league/badge/vcgyu71686617925.png" },
      { id: "4338", name: "Belgian Pro League", displayName: "Belgian Pro", badge: "https://r2.thesportsdb.com/images/media/league/badge/mjit7n1593634474.png" },
      { id: "4346", name: "American Major League Soccer", displayName: "MLS", badge: "https://r2.thesportsdb.com/images/media/league/badge/dqo6r91549878326.png" },
      { id: "4347", name: "Mexican Liga MX", displayName: "Liga MX", badge: "https://r2.thesportsdb.com/images/media/league/badge/denok11707459183.png" },
      { id: "4351", name: "Brazilian Serie A", displayName: "Brazilian Serie A", badge: "https://r2.thesportsdb.com/images/media/league/badge/dmu4oq1753306626.png" },
      { id: "4406", name: "Argentinian Primera Division", displayName: "Arg Primera", badge: "https://r2.thesportsdb.com/images/media/league/badge/1vslha1589960216.png" },
      { id: "4356", name: "Australian A-League", displayName: "A-League", badge: "https://r2.thesportsdb.com/images/media/league/badge/2u78lm1638459575.png" },
      { id: "4480", name: "UEFA Champions League", displayName: "UCL", badge: "https://r2.thesportsdb.com/images/media/league/badge/facv1u1742998896.png" },
      { id: "4481", name: "UEFA Europa League", displayName: "Europa League", badge: "https://r2.thesportsdb.com/images/media/league/badge/mlsr7d1718774547.png" },
      { id: "5324", name: "UEFA Conference League", displayName: "Conf League", badge: "https://r2.thesportsdb.com/images/media/league/badge/qs4p6z1659099588.png" },
      { id: "4501", name: "Copa Libertadores", displayName: "Libertadores", badge: "https://r2.thesportsdb.com/images/media/league/badge/9shr931685425181.png" },
      { id: "4724", name: "Copa Sudamericana", displayName: "Sudamericana", badge: "https://r2.thesportsdb.com/images/media/league/badge/9yynq01685425243.png" },
      { id: "4329", name: "English Championship", displayName: "Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/ty5a681688770169.png" },
      { id: "4952", name: "Croatian Druga HNL", displayName: "Prva NL", badge: "https://r2.thesportsdb.com/images/media/league/badge/2bdq071615833896.png" },
      { id: "4521", name: "American NWSL", displayName: "NWSL", badge: "https://r2.thesportsdb.com/images/media/league/badge/srpnpi1551383087.png" },
      { id: "4805", name: "Australian A-League Women", displayName: "A-League Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/1sk49c1638459590.png" },
      { id: "5485", name: "AFC Challenge League", displayName: "AFC Challenge", badge: "https://r2.thesportsdb.com/images/media/league/badge/ctg73b1721497942.png" },
      { id: "4617", name: "Albanian Superliga", displayName: "Albanian SL", badge: "https://r2.thesportsdb.com/images/media/league/badge/torbg81711693424.png" },
      { id: "4753", name: "Algerian Ligue 1", displayName: "Algerian L1", badge: "https://r2.thesportsdb.com/images/media/league/badge/ac4ga11714895756.png" },
      { id: "4618", name: "Andorran 1a Divisió", displayName: "Andorra", badge: "https://r2.thesportsdb.com/images/media/league/badge/3ajfun1578786604.png" },
      { id: "5229", name: "Angolan Girabola", displayName: "Angola", badge: "https://r2.thesportsdb.com/images/media/league/badge/joa52o1645195859.png" },
      { id: "4619", name: "Armenian Premier League", displayName: "Armenia", badge: "https://r2.thesportsdb.com/images/media/league/badge/h4o8zq1687710680.png" },
      { id: "5230", name: "Aruban Division di Honor", displayName: "Aruba", badge: "https://r2.thesportsdb.com/images/media/league/badge/65ra8b1645196203.png" },
      { id: "4693", name: "Azerbaijani Premier League", displayName: "Azerbaijan", badge: "https://r2.thesportsdb.com/images/media/league/badge/urt6hw1614346226.png" },
      { id: "4826", name: "Bahrain Premier League", displayName: "Bahrain", badge: "https://r2.thesportsdb.com/images/media/league/badge/4wvjoo1589804487.png" },
      { id: "5078", name: "Bangladesh Premier League", displayName: "Bangladesh", badge: "https://r2.thesportsdb.com/images/media/league/badge/npx9wc1625520096.png" },
      { id: "4622", name: "Belarus Vyscha Liga", displayName: "Belarus", badge: "https://r2.thesportsdb.com/images/media/league/badge/nb8xtg1656531943.png" },
      { id: "5231", name: "Benin Championnat National", displayName: "Benin", badge: "https://r2.thesportsdb.com/images/media/league/badge/ayss9d1749544030.png" },
      { id: "5232", name: "Bermuda Premier League", displayName: "Bermuda", badge: "https://r2.thesportsdb.com/images/media/league/badge/ttzj2d1645208744.png" },
      { id: "4685", name: "Bolivian Primera División", displayName: "Bolivia", badge: "https://r2.thesportsdb.com/images/media/league/badge/67roii1614772915.png" },
      { id: "4624", name: "Bosnian Premier Liga", displayName: "Bosnia", badge: "https://r2.thesportsdb.com/images/media/league/badge/kvmxlj1721283327.png" },
      { id: "5233", name: "Botswana Premier League", displayName: "Botswana", badge: "https://r2.thesportsdb.com/images/media/league/badge/1wybwn1712733338.png" },
      { id: "5201", name: "Brazil Brasileiro Women", displayName: "Brazil Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/es83901752264616.png" },
      { id: "5676", name: "Brazilian Campeonato Acreano", displayName: "Acreano", badge: "https://r2.thesportsdb.com/images/media/league/badge/4d9le21754492204.png" },
      { id: "5677", name: "Brazilian Campeonato Alagoano", displayName: "Alagoano", badge: "https://r2.thesportsdb.com/images/media/league/badge/wcmbrw1754493117.png" },
      { id: "5678", name: "Brazilian Campeonato Amapaense", displayName: "Amapaense", badge: "https://r2.thesportsdb.com/images/media/league/badge/6sy3xd1754493984.png" },
      { id: "5679", name: "Brazilian Campeonato Amazonense", displayName: "Amazonense", badge: "https://r2.thesportsdb.com/images/media/league/badge/t9nfej1754494955.png" },
      { id: "5684", name: "Brazilian Campeonato Baiano", displayName: "Baiano", badge: "https://r2.thesportsdb.com/images/media/league/badge/ehk7hw1756631450.png" },
      { id: "5685", name: "Brazilian Campeonato Brasiliense", displayName: "Brasiliense", badge: "https://r2.thesportsdb.com/images/media/league/badge/7z9n1v1756632496.png" },
      { id: "5686", name: "Brazilian Campeonato Capixaba", displayName: "Capixaba", badge: "https://r2.thesportsdb.com/images/media/league/badge/5f2rcm1756633054.png" },
      { id: "5688", name: "Brazilian Campeonato Carioca", displayName: "Carioca", badge: "https://r2.thesportsdb.com/images/media/league/badge/aewl9f1756636968.png" },
      { id: "5687", name: "Brazilian Campeonato Catarinense", displayName: "Catarinense", badge: "https://r2.thesportsdb.com/images/media/league/badge/rvn16n1756635839.png" },
      { id: "5689", name: "Brazilian Campeonato Cearense", displayName: "Cearense", badge: "https://r2.thesportsdb.com/images/media/league/badge/gm4k7s1756639011.png" },
      { id: "5691", name: "Brazilian Campeonato Gaucho", displayName: "Gaucho", badge: "https://r2.thesportsdb.com/images/media/league/badge/9v3mpn1756639595.png" },
      { id: "4626", name: "Bulgarian First League", displayName: "Bulgaria", badge: "https://r2.thesportsdb.com/images/media/league/badge/nujbma1730047938.png" },
    ],
  },
{
    id: "basketball",
    name: "Basketball",
    iconName: "basketball",
    iconType: "svg",
    leagues: [
      { id: "4734", name: "Argentine LNB", displayName: "Argentine LNB", badge: "https://r2.thesportsdb.com/images/media/league/badge/exea481740429840.png" },
      { id: "5351", name: "NBL1 West", displayName: "NBL1 West", badge: "https://r2.thesportsdb.com/images/media/league/badge/rnq1o11672323707.png" },
      { id: "4434", name: "Australian NBL", displayName: "Australian NBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/gvz6vb1726086476.png" },
      { id: "5671", name: "NBL1 South", displayName: "NBL1 South", badge: "https://r2.thesportsdb.com/images/media/league/badge/i6p14a1754389758.png" },
      { id: "5670", name: "NBL1 North", displayName: "NBL1 North", badge: "https://r2.thesportsdb.com/images/media/league/badge/773nz11754386845.png" },
      { id: "5669", name: "NBL1 East", displayName: "NBL1 East", badge: "https://r2.thesportsdb.com/images/media/league/badge/olkqwi1754384283.png" },
      { id: "5113", name: "Australian WNBL", displayName: "Australian WNBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/hnate81749406441.png" },
      { id: "5667", name: "NBL1 Central", displayName: "NBL1 Central", badge: "https://r2.thesportsdb.com/images/media/league/badge/8qtlej1754382440.png" },
      { id: "5265", name: "Austrian Basketball Superliga", displayName: "Austrian Basketball Superliga", badge: "https://r2.thesportsdb.com/images/media/league/badge/mbatnq1650474025.png" },
      { id: "4579", name: "Belgian PBL", displayName: "Belgian PBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/3h3k6v1572364943.png" },
      { id: "5270", name: "BNXT League", displayName: "BNXT League", badge: "https://r2.thesportsdb.com/images/media/league/badge/jo51vy1726914501.png" },
      { id: "5130", name: "Basketball Championship of Bosnia and Herzegovina", displayName: "Basketball Championship of ...", badge: "https://r2.thesportsdb.com/images/media/league/badge/kw78xn1642015404.png" },
      { id: "5128", name: "Bulgarian NBL", displayName: "Bulgarian NBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/6qg55i1642013186.png" },
      { id: "5266", name: "Canadian Elite Basketball League", displayName: "Canadian Elite Basketball L...", badge: "https://r2.thesportsdb.com/images/media/league/badge/95hd3l1687527980.png" },
      { id: "4442", name: "Chinese CBA", displayName: "Chinese CBA", badge: "https://r2.thesportsdb.com/images/media/league/badge/peygv31522257103.png" },
      { id: "5131", name: "Chinese WCBA", displayName: "Chinese WCBA", badge: "https://r2.thesportsdb.com/images/media/league/badge/1qn7hi1704657330.png" },
      { id: "5705", name: "Croatian Premijer Liga", displayName: "Croatian Premijer Liga", badge: "https://www.thesportsdb.com/images/media/league/badge/3mo0i41759932471.png" },
      { id: "5129", name: "Cyprus Basketball Division A", displayName: "Cyprus Basketball Division A", badge: "https://r2.thesportsdb.com/images/media/league/badge/yxzu071642013544.png" },
      { id: "5405", name: "Czech NBL", displayName: "Czech NBL", badge: "https://www.thesportsdb.com/images/media/league/badge/2qxhi61759326394.png" },
      { id: "5114", name: "Danish Basketligaen", displayName: "Danish Basketligaen", badge: "https://r2.thesportsdb.com/images/media/league/badge/vb89k11642005069.png" },
      { id: "5115", name: "Estonian Korvpalli Meistriliiga", displayName: "Estonian Korvpalli Meistril...", badge: "https://r2.thesportsdb.com/images/media/league/badge/vf1r7o1642005606.png" },
      { id: "5607", name: "FIBA Europe Cup", displayName: "FIBA Europe Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/2k38a81746275001.png" },
      { id: "4892", name: "EuroLeague Women", displayName: "EuroLeague Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/m70fvx1757702450.png" },
      { id: "4548", name: "Basketball Champions League", displayName: "Basketball Champions League", badge: "https://r2.thesportsdb.com/images/media/league/badge/6dfp5j1576751638.png" },
      { id: "4890", name: "EuroBasket Women", displayName: "EuroBasket Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/zau5831742998665.png" },
      { id: "4831", name: "FIBA EuroBasket", displayName: "FIBA EuroBasket", badge: "https://r2.thesportsdb.com/images/media/league/badge/ztfjmi1704394222.png" },
      { id: "4547", name: "EuroCup Basketball", displayName: "EuroCup Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/w54nor1554757326.png" },
      { id: "4546", name: "EuroLeague Basketball", displayName: "EuroLeague Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/7xjtuy1554397263.png" },
      { id: "5706", name: "Adriatic ABA League 2", displayName: "Adriatic ABA League 2", badge: "https://www.thesportsdb.com/images/media/league/badge/7cdyqn1760037015.png" },
      { id: "5621", name: "FIBA Europe SuperCup Women", displayName: "FIBA Europe SuperCup Women", badge: "https://www.thesportsdb.com/images/media/league/badge/q3xo2w1759344442.png" },
      { id: "4477", name: "Adriatic ABA League", displayName: "Adriatic ABA League", badge: "https://www.thesportsdb.com/images/media/league/badge/stce0n1758213648.png" },
      { id: "5620", name: "EuroCup Women", displayName: "EuroCup Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/d07uch1746285374.png" },
      { id: "5116", name: "Finnish Korisliiga", displayName: "Finnish Korisliiga", badge: "https://r2.thesportsdb.com/images/media/league/badge/9szzvr1642005935.png" },
      { id: "4423", name: "French LNB", displayName: "French LNB", badge: "https://r2.thesportsdb.com/images/media/league/badge/60detm1757608684.png" },
      { id: "4577", name: "French LNB Pro B", displayName: "French LNB Pro B", badge: "https://r2.thesportsdb.com/images/media/league/badge/0yjbmz1754268940.png" },
      { id: "5381", name: "LNB Pro A Leaders Cup", displayName: "LNB Pro A Leaders Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/6j9mnt1739557356.png" },
      { id: "5380", name: "Coupe de France de Basket", displayName: "Coupe de France de Basket", badge: "https://r2.thesportsdb.com/images/media/league/badge/uzqrc31685987408.png" },
      { id: "5623", name: "Ligue Féminine de Basketball", displayName: "Ligue Féminine de Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/o5r1we1746284587.png" },
      { id: "5694", name: "French Nationale Masculine 1", displayName: "French Nationale Masculine 1", badge: "https://r2.thesportsdb.com/images/media/league/badge/6ucfc81757601421.png" },
      { id: "4441", name: "German BBL", displayName: "German BBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/ssgkzq1550038219.png" },
      { id: "5132", name: "German ProA", displayName: "German ProA", badge: "https://r2.thesportsdb.com/images/media/league/badge/eoti3f1642019931.png" },
      { id: "4452", name: "Greek Basket League", displayName: "Greek Basket League", badge: "https://r2.thesportsdb.com/images/media/league/badge/z39ouv1667032625.png" },
      { id: "4580", name: "Hungarian Nemzeti Bajnokság IA", displayName: "Hungarian Nemzeti Bajnokság IA", badge: "https://r2.thesportsdb.com/images/media/league/badge/xypme21571908372.png" },
      { id: "5117", name: "Icelandic Úrvalsdeild karla", displayName: "Icelandic Úrvalsdeild karla", badge: "https://www.thesportsdb.com/images/media/league/badge/9u8l6e1759491006.png" },
      { id: "4474", name: "Israeli Basketball Premier League", displayName: "Israeli Basketball Premier ...", badge: "https://r2.thesportsdb.com/images/media/league/badge/du6oy91573142280.png" },
      { id: "5271", name: "Israeli Basketball National League", displayName: "Israeli Basketball National...", badge: "https://r2.thesportsdb.com/images/media/league/badge/qy7ubp1737282301.png" },
      { id: "5595", name: "Israeli Basketball State Cup", displayName: "Israeli Basketball State Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/5y0vg81742381206.png" },
      { id: "4433", name: "Italian Lega Basket", displayName: "Italian Lega Basket", badge: "https://r2.thesportsdb.com/images/media/league/badge/zenfi61667129026.png" },
      { id: "5596", name: "Lega Basket Femminile", displayName: "Lega Basket Femminile", badge: "https://r2.thesportsdb.com/images/media/league/badge/5vs98z1742466645.png" },
      { id: "5377", name: "Italian Serie A2", displayName: "Italian Serie A2", badge: "https://r2.thesportsdb.com/images/media/league/badge/yqqexa1677596004.png" },
      { id: "5409", name: "Italian Basketball Cup", displayName: "Italian Basketball Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/ask2641696762126.png" },
      { id: "5408", name: "Italian Basketball Supercup", displayName: "Italian Basketball Supercup", badge: "https://r2.thesportsdb.com/images/media/league/badge/shv7dm1696761835.png" },
      { id: "4977", name: "Japanese B1 League", displayName: "Japanese B1 League", badge: "https://r2.thesportsdb.com/images/media/league/badge/vcx6gw1745501883.png" },
      { id: "5118", name: "Kosovo Basketball Superleague", displayName: "Kosovo Basketball Superleague", badge: "https://www.thesportsdb.com/images/media/league/badge/o77vh81759568536.png" },
      { id: "4478", name: "Lithuanian LKL", displayName: "Lithuanian LKL", badge: "https://r2.thesportsdb.com/images/media/league/badge/7nrqn21745083569.png" },
      { id: "5133", name: "Lithuanian NKL", displayName: "Lithuanian NKL", badge: "https://r2.thesportsdb.com/images/media/league/badge/3ukv611642020760.png" },
      { id: "5120", name: "Macedonian Superleague", displayName: "Macedonian Superleague", badge: "https://r2.thesportsdb.com/images/media/league/badge/08vnlh1642008381.png" },
      { id: "5119", name: "Mexican LNBP", displayName: "Mexican LNBP", badge: "https://r2.thesportsdb.com/images/media/league/badge/u6ez4m1642007851.png" },
      { id: "5066", name: "New Zealand NBL", displayName: "New Zealand NBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/y1xqgl1745502379.png" },
      { id: "4578", name: "Polish Basketball League", displayName: "Polish Basketball League", badge: "https://r2.thesportsdb.com/images/media/league/badge/ebuhow1737138503.png" },
      { id: "4476", name: "Russian VTB United League", displayName: "Russian VTB United League", badge: "https://r2.thesportsdb.com/images/media/league/badge/5jibk81521140717.png" },
      { id: "5121", name: "Basketball League of Serbia", displayName: "Basketball League of Serbia", badge: "https://r2.thesportsdb.com/images/media/league/badge/1fnbpg1642009229.png" },
      { id: "5122", name: "Slovak Basketball League", displayName: "Slovak Basketball League", badge: "https://r2.thesportsdb.com/images/media/league/badge/pm9zdg1745498765.png" },
      { id: "5123", name: "Slovenian Basketball League", displayName: "Slovenian Basketball League", badge: "https://r2.thesportsdb.com/images/media/league/badge/uxzv1y1745498230.png" },
      { id: "5124", name: "Korean Basketball League", displayName: "Korean Basketball League", badge: "https://r2.thesportsdb.com/images/media/league/badge/d9f3ve1642011224.png" },
      { id: "4833", name: "Spanish Supercup of Basketball", displayName: "Spanish Supercup of Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/uj25ue1664095737.png" },
      { id: "4832", name: "Spanish Copa del Rey de Baloncesto", displayName: "Spanish Copa del Rey de Bal...", badge: "https://r2.thesportsdb.com/images/media/league/badge/yzvlm71674667018.png" },
      { id: "5134", name: "Spanish Primera FEB", displayName: "Spanish Primera FEB", badge: "https://r2.thesportsdb.com/images/media/league/badge/sfgh3l1727082881.png" },
      { id: "5486", name: "Spanish Liga Femenina de Baloncesto", displayName: "Spanish Liga Femenina de Ba...", badge: "https://r2.thesportsdb.com/images/media/league/badge/igl7v11721543579.png" },
      { id: "5487", name: "Spanish Supercopa de Espana de Baloncesto Femenino", displayName: "Spanish Supercopa de Espana...", badge: "https://r2.thesportsdb.com/images/media/league/badge/w9b8ab1721558061.png" },
      { id: "5488", name: "Spanish Copa de la Reina de Baloncesto", displayName: "Spanish Copa de la Reina de...", badge: "https://r2.thesportsdb.com/images/media/league/badge/52ljst1721550628.png" },
      { id: "5509", name: "Spanish Segunda FEB", displayName: "Spanish Segunda FEB", badge: "https://r2.thesportsdb.com/images/media/league/badge/r1me5w1730275794.png" },
      { id: "4408", name: "Spanish Liga ACB", displayName: "Spanish Liga ACB", badge: "https://r2.thesportsdb.com/images/media/league/badge/4n3h6z1572778356.png" },
      { id: "5125", name: "Swiss SB League", displayName: "Swiss SB League", badge: "https://r2.thesportsdb.com/images/media/league/badge/qtj9j01642011596.png" },
      { id: "5267", name: "Taiwan SBL", displayName: "Taiwan SBL", badge: "https://r2.thesportsdb.com/images/media/league/badge/p6o0hn1650474300.png" },
      { id: "4475", name: "Turkish Basketbol Super Ligi", displayName: "Turkish Basketbol Super Ligi", badge: "https://r2.thesportsdb.com/images/media/league/badge/bnkkgh1551517800.png" },
      { id: "5507", name: "Turkish Basketball Cup", displayName: "Turkish Basketball Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/d9gjnh1730243677.png" },
      { id: "5508", name: "Turkish Basketball Presidential Cup", displayName: "Turkish Basketball Presiden...", badge: "https://r2.thesportsdb.com/images/media/league/badge/rpnpei1730245204.png" },
      { id: "5693", name: "Turkish Basketball First League", displayName: "Turkish Basketball First Le...", badge: "https://r2.thesportsdb.com/images/media/league/badge/3incjb1757585643.png" },
      { id: "5126", name: "Ukrainian Basketball SuperLeague", displayName: "Ukrainian Basketball SuperL...", badge: "https://r2.thesportsdb.com/images/media/league/badge/w1oqxa1737283447.png" },
      { id: "5127", name: "Super League Basketball Women", displayName: "Super League Basketball Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/bhrk3k1732388961.png" },
      { id: "4431", name: "Super League Basketball", displayName: "Super League Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/zeyqgd1728457275.png" },
      { id: "4387", name: "NBA", displayName: "NBA", badge: "https://r2.thesportsdb.com/images/media/league/badge/frdjqy1536585083.png" },
      { id: "4607", name: "NCAA Division I Basketball Mens", displayName: "NCAA Division I Basketball ...", badge: "https://r2.thesportsdb.com/images/media/league/badge/ibf3d21731087087.png" },
      { id: "4850", name: "FIBA AmeriCup", displayName: "FIBA AmeriCup", badge: "https://r2.thesportsdb.com/images/media/league/badge/nhcyww1751721740.png" },
      { id: "4516", name: "WNBA", displayName: "WNBA", badge: "https://r2.thesportsdb.com/images/media/league/badge/47llb31573154455.png" },
      { id: "5399", name: "NBA Summer League", displayName: "NBA Summer League", badge: "https://r2.thesportsdb.com/images/media/league/badge/wo5fgz1689156222.png" },
      { id: "5593", name: "NCAA National Invitation Tournament", displayName: "NCAA National Invitation To...", badge: "https://r2.thesportsdb.com/images/media/league/badge/0aoy9g1742379125.png" },
      { id: "5506", name: "NBA Cup", displayName: "NBA Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/iv3t3o1730139992.png" },
      { id: "4388", name: "NBA G League", displayName: "NBA G League", badge: "https://r2.thesportsdb.com/images/media/league/badge/u96k271549480775.png" },
      { id: "5153", name: "Basketball All-Star Games", displayName: "Basketball All-Star Games", badge: "https://r2.thesportsdb.com/images/media/league/badge/jyzwza1737707936.png" },
      { id: "5622", name: "Unrivaled Basketball", displayName: "Unrivaled Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/71mier1746291561.png" },
      { id: "5272", name: "NIT", displayName: "NIT", badge: "https://r2.thesportsdb.com/images/media/league/badge/cw9ad21742381043.png" },
      { id: "5268", name: "Vietnam Basketball Association", displayName: "Vietnam Basketball Association", badge: "https://www.thesportsdb.com/images/media/league/badge/o1bhz81759931895.png" },
      { id: "4836", name: "_No League Basketball", displayName: "_No League Basketball", badge: "https://www.thesportsdb.com/images/media/league/badge/g3iw981761017518.png" },
      { id: "5273", name: "Basketball Champions League Americas", displayName: "Basketball Champions League...", badge: "https://r2.thesportsdb.com/images/media/league/badge/n0e0lv1746347424.png" },
      { id: "4891", name: "FIBA Womens World Cup", displayName: "FIBA Womens World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/tlkdaq1726930250.png" },
      { id: "5358", name: "Commonwealth Games 3x3 Basketball", displayName: "Commonwealth Games 3x3 Bask...", badge: "https://r2.thesportsdb.com/images/media/league/badge/2wmyjx1677837133.png" },
      { id: "5383", name: "Olympics Basketball Women", displayName: "Olympics Basketball Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/d791a41689153644.png" },
      { id: "5387", name: "FIBA Womens Asia Cup", displayName: "FIBA Womens Asia Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/qqt0dn1751188385.png" },
      { id: "5406", name: "Basketball International Friendlies", displayName: "Basketball International Fr...", badge: "https://r2.thesportsdb.com/images/media/league/badge/ehbh3t1721467383.png" },
      { id: "5407", name: "Basketball International Friendlies Women", displayName: "Basketball International Fr...", badge: "https://r2.thesportsdb.com/images/media/league/badge/yghyt21697045194.png" },
      { id: "5420", name: "Asian Games Basketball Women", displayName: "Asian Games Basketball Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/qs8hqf1705068451.png" },
      { id: "4549", name: "FIBA Basketball World Cup", displayName: "FIBA Basketball World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/97pb7g1670404826.png" },
      { id: "4518", name: "_Defunct Basketball Teams", displayName: "_Defunct Basketball Teams", badge: "https://r2.thesportsdb.com/images/media/league/badge/4e7fi41550089807.png" },
      { id: "5020", name: "Olympics Basketball", displayName: "Olympics Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/a048d11687509653.png" },
      { id: "5419", name: "Asian Games Basketball", displayName: "Asian Games Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/csak3w1705068422.png" },
      { id: "4982", name: "FIBA Womens AmeriCup", displayName: "FIBA Womens AmeriCup", badge: "https://r2.thesportsdb.com/images/media/league/badge/9rdofv1751187447.png" },
      { id: "5633", name: "Basketball Champions League Asia", displayName: "Basketball Champions League...", badge: "https://r2.thesportsdb.com/images/media/league/badge/4hw7eg1750421064.png" },
      { id: "5478", name: "Olympics 3x3 Basketball Women", displayName: "Olympics 3x3 Basketball Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/b55edf1687509684.png" },
      { id: "5021", name: "Olympics 3x3 Basketball", displayName: "Olympics 3x3 Basketball", badge: "https://r2.thesportsdb.com/images/media/league/badge/b55edf1687509684.png" },
      { id: "5269", name: "Basketball Africa League", displayName: "Basketball Africa League", badge: "https://r2.thesportsdb.com/images/media/league/badge/azbffo1650474485.png" },
      { id: "4898", name: "FIBA Asia Cup", displayName: "FIBA Asia Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/abbrq01744542947.png" },
      { id: "5500", name: "FIBA Intercontinental Cup", displayName: "FIBA Intercontinental Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/4z3dxw1730126748.png" },
      { id: "4897", name: "FIBA AfroBasket", displayName: "FIBA AfroBasket", badge: "https://r2.thesportsdb.com/images/media/league/badge/pedqcz1751193892.png" },
      { id: "5505", name: "FIBA Womens AfroBasket", displayName: "FIBA Womens AfroBasket", badge: "https://r2.thesportsdb.com/images/media/league/badge/j9arj61751191281.png" },
      { id: "5599", name: "FIBA West Asia Super League", displayName: "FIBA West Asia Super League", badge: "https://r2.thesportsdb.com/images/media/league/badge/72tipa1746273915.png" }
    ],
  },
  {
    id: "american-football",
    name: "American Football",
    iconName: "american-football",
    iconType: "svg",
    leagues: [
      { id: "4391", name: "NFL", displayName: "NFL", badge: "https://r2.thesportsdb.com/images/media/league/badge/g85fqz1662057187.png" },
      { id: "4479", name: "NCAA Division 1", displayName: "NCAA Division 1", badge: "https://www.thesportsdb.com/images/media/league/badge/hm3cyr1758455622.png" },
      { id: "4405", name: "CFL", displayName: "CFL", badge: "https://r2.thesportsdb.com/images/media/league/badge/ffypv51488739128.png" },
      { id: "5434", name: "UFL", displayName: "UFL", badge: "https://r2.thesportsdb.com/images/media/league/badge/cczvsw1710531183.png" },
      { id: "4718", name: "XFL", displayName: "XFL", badge: "https://r2.thesportsdb.com/images/media/league/badge/ctbxuh1676896770.png" },
      { id: "5262", name: "United States Football League", displayName: "United States Football Le...", badge: "https://r2.thesportsdb.com/images/media/league/badge/fphuot1645222187.png" },
      { id: "5063", name: "European League of Football", displayName: "European League of Football", badge: "https://r2.thesportsdb.com/images/media/league/badge/vxfubq1625238915.png" },
      { id: "5336", name: "GFL", displayName: "GFL", badge: "https://r2.thesportsdb.com/images/media/league/badge/zt1ksf1719819947.png" },
      { id: "4470", name: "Arena Football League", displayName: "Arena Football League", badge: "https://r2.thesportsdb.com/images/media/league/badge/uny2591711637721.png" },
      { id: "4471", name: "Indoor Football League", displayName: "Indoor Football League", badge: "https://r2.thesportsdb.com/images/media/league/badge/hsrtzo1587394827.png" },
      { id: "4473", name: "National Arena League", displayName: "National Arena League", badge: "https://r2.thesportsdb.com/images/media/league/badge/dcmjxa1512642332.png" },
      { id: "5350", name: "U Sports Football League", displayName: "U Sports Football League", badge: "https://r2.thesportsdb.com/images/media/league/badge/bh13yw1672338490.png" },
      { id: "5154", name: "American Football All-Star Games", displayName: "American Football All-Sta...", badge: "https://r2.thesportsdb.com/images/media/league/badge/ts54281644226904.png" },
      { id: "5482", name: "American Football League", displayName: "American Football League", badge: "https://r2.thesportsdb.com/images/media/league/badge/hstx2k1719402847.png" },
      { id: "4552", name: "AAF", displayName: "AAF", badge: "https://r2.thesportsdb.com/images/media/league/badge/e7gxjz1554662558.png" },
      { id: "4809", name: "_Defunct American Football Teams", displayName: "_Defunct American Footbal...", badge: "https://r2.thesportsdb.com/images/media/league/badge/3hc0re1624658586.png" },
      { id: "4839", name: "_No League American Football", displayName: "_No League American Football", badge: "https://r2.thesportsdb.com/images/media/league/badge/xxwwwt1421422891.png" },
    ],
  },
  {
    id: "baseball",
    name: "Baseball",
    iconName: "baseball",
    iconType: "svg",
    leagues: [
      { id: "4424", name: "MLB", displayName: "MLB", badge: "https://r2.thesportsdb.com/images/media/league/badge/c5r83j1521893739.png" },
      { id: "4427", name: "Can-Am", displayName: "Can-Am", badge: "https://r2.thesportsdb.com/images/media/league/badge/tytqpw1424020318.png" },
      { id: "4428", name: "Frontier League", displayName: "Frontier League", badge: "https://r2.thesportsdb.com/images/media/league/badge/qx1gft1741870094.png" },
      { id: "4591", name: "Nippon Baseball League", displayName: "Nippon Baseball League", badge: "https://r2.thesportsdb.com/images/media/league/badge/lk85rg1575038781.png" },
      { id: "4592", name: "_Defunct Baseball Teams", displayName: "_Defunct Baseball Teams", badge: "https://r2.thesportsdb.com/images/media/league/badge/19bnh41575039933.png" },
      { id: "4830", name: "Korean KBO League", displayName: "Korean KBO League", badge: "https://r2.thesportsdb.com/images/media/league/badge/qfr1hx1589707979.png" },
      { id: "4837", name: "_No League Baseball", displayName: "_No League Baseball", badge: "https://r2.thesportsdb.com/images/media/league/badge/xxwwwt1421422891.png" },
      { id: "5018", name: "Olympics Baseball", displayName: "Olympics Baseball", badge: "https://r2.thesportsdb.com/images/media/league/badge/lev6yv1687509593.png" },
      { id: "5019", name: "Olympics SoftBall", displayName: "Olympics SoftBall", badge: "https://r2.thesportsdb.com/images/media/league/badge/raygji1687509607.png" },
      { id: "5064", name: "Liga Mexicana de Béisbol", displayName: "Liga Mexicana de Béisbol", badge: "https://r2.thesportsdb.com/images/media/league/badge/m3eza81748934903.png" },
      { id: "5065", name: "Pacific Coast League", displayName: "Pacific Coast League", badge: "https://r2.thesportsdb.com/images/media/league/badge/8qykag1655390427.png" },
      { id: "5444", name: "International League", displayName: "International League", badge: "https://r2.thesportsdb.com/images/media/league/badge/ph6had1713522942.png" },
      { id: "5107", name: "Australian Baseball League", displayName: "Australian Baseball Leagu...", badge: "https://r2.thesportsdb.com/images/media/league/badge/jlnr611641806780.png" },
      { id: "5108", name: "Cuban National Series", displayName: "Cuban National Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/aobwn81641807695.png" },
      { id: "5109", name: "Mexican Pacific League", displayName: "Mexican Pacific League", badge: "https://r2.thesportsdb.com/images/media/league/badge/vefg091641808224.png" },
      { id: "5110", name: "Honkbal Hoofdklasse", displayName: "Honkbal Hoofdklasse", badge: "https://r2.thesportsdb.com/images/media/league/badge/jgztgd1641808397.png" },
      { id: "5111", name: "Chinese Professional Baseball League", displayName: "Chinese Professional Base...", badge: "https://r2.thesportsdb.com/images/media/league/badge/c3vetj1655924198.png" },
      { id: "5112", name: "Venezuelan Professional Baseball League", displayName: "Venezuelan Professional B...", badge: "https://r2.thesportsdb.com/images/media/league/badge/b8n0rt1641809153.png" },
      { id: "5437", name: "Baseball All-Star Games", displayName: "Baseball All-Star Games", badge: "https://r2.thesportsdb.com/images/media/league/badge/o1y7f11713454967.png" },
    ],
  },
  {
    id: "ice-hockey",
    name: "Ice Hockey",
    iconName: "ice-hockey",
    iconType: "svg",
    leagues: [
      { id: "4380", name: "NHL", displayName: "NHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/4cem2k1619616539.png" },
      { id: "5346", name: "NCAA Division 1 Ice Hockey", displayName: "NCAA Division 1 Ice Hockey", badge: "https://www.thesportsdb.com/images/media/league/badge/f4ktm91758455722.png" },
      { id: "4738", name: "American AHL", displayName: "American AHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/bm25ej1582197507.png" },
      { id: "4916", name: "American ECHL", displayName: "American ECHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/zy5yar1615490977.png" },
      { id: "4917", name: "American USHL", displayName: "American USHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/dz8gnm1615491151.png" },
      { id: "4918", name: "American FPHL", displayName: "American FPHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/o925vl1615491473.png" },
      { id: "5164", name: "American SPHL", displayName: "American SPHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/3lw12d1644535657.png" },
      { id: "5157", name: "American Premier Hockey Federation", displayName: "American Premier Hockey F...", badge: "https://r2.thesportsdb.com/images/media/league/badge/v1t5le1645096681.png" },
      { id: "5159", name: "Canadian OHL", displayName: "Canadian OHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/y4z5ks1644535179.png" },
      { id: "5160", name: "Canadian WHL", displayName: "Canadian WHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/94w3kx1644535361.png" },
      { id: "5161", name: "Canadian QMJHL", displayName: "Canadian QMJHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/3nofen1644535248.png" },
      { id: "5643", name: "Canadian Memorial Cup", displayName: "Canadian Memorial Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/zs1qv51750422880.png" },
      { id: "4920", name: "Russian KHL", displayName: "Russian KHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/tfmf8l1615492008.png" },
      { id: "4919", name: "Russian VHL", displayName: "Russian VHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/tyad1s1630125596.png" },
      { id: "4419", name: "Swedish Hockey League", displayName: "Swedish Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/95fnqb1547547893.png" },
      { id: "5162", name: "Swedish Hockey Allsvenskan", displayName: "Swedish Hockey Allsvenskan", badge: "https://r2.thesportsdb.com/images/media/league/badge/xcb4bz1644535507.png" },
      { id: "5158", name: "Swedish Womens Hockey League", displayName: "Swedish Womens Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/iagjdj1644535046.png" },
      { id: "4925", name: "German DEL", displayName: "German DEL", badge: "https://r2.thesportsdb.com/images/media/league/badge/ttrhds1615493883.png" },
      { id: "4936", name: "German DEL 2", displayName: "German DEL 2", badge: "https://r2.thesportsdb.com/images/media/league/badge/ph2dmw1615592487.png" },
      { id: "4931", name: "Finnish Liiga", displayName: "Finnish Liiga", badge: "https://r2.thesportsdb.com/images/media/league/badge/niqb7d1730472609.png" },
      { id: "4935", name: "Finnish Mestis", displayName: "Finnish Mestis", badge: "https://r2.thesportsdb.com/images/media/league/badge/kpsk5m1615592034.png" },
      { id: "4934", name: "Swiss National League", displayName: "Swiss National League", badge: "https://r2.thesportsdb.com/images/media/league/badge/bibbao1626129533.png" },
      { id: "5163", name: "Swiss League", displayName: "Swiss League", badge: "https://r2.thesportsdb.com/images/media/league/badge/s4dm1f1644535592.png" },
      { id: "4923", name: "Czech Extraliga", displayName: "Czech Extraliga", badge: "https://r2.thesportsdb.com/images/media/league/badge/mx7f7p1615493091.png" },
      { id: "4932", name: "Slovak Extraliga", displayName: "Slovak Extraliga", badge: "https://r2.thesportsdb.com/images/media/league/badge/sjg7yf1615590325.png" },
      { id: "4929", name: "Slovak Hockey League", displayName: "Slovak Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/19y0ho1615496565.png" },
      { id: "4926", name: "Norwegian Fjordkraft-ligaen", displayName: "Norwegian Fjordkraft-lig...", badge: "https://r2.thesportsdb.com/images/media/league/badge/lpfdvc1697194460.png" },
      { id: "4930", name: "Danish Metal Ligaen", displayName: "Danish Metal Ligaen", badge: "https://r2.thesportsdb.com/images/media/league/badge/1q4in31615589789.png" },
      { id: "4927", name: "French Ligue Magnus", displayName: "French Ligue Magnus", badge: "https://r2.thesportsdb.com/images/media/league/badge/qgchfz1615495275.png" },
      { id: "4933", name: "Austrian ICE Hockey League", displayName: "Austrian ICE Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/ny26z31694527818.png" },
      { id: "4928", name: "Polish Hockey League", displayName: "Polish Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/tt4t7w1615642845.png" },
      { id: "4924", name: "Belarusian Extraleague", displayName: "Belarusian Extraleague", badge: "https://r2.thesportsdb.com/images/media/league/badge/57iwzz1615839650.png" },
      { id: "4922", name: "Ukrainian UHL", displayName: "Ukrainian UHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/y3siyb1615492807.png" },
      { id: "4921", name: "Latvian Optibet Hockey League", displayName: "Latvian Optibet Hockey Le...", badge: "https://r2.thesportsdb.com/images/media/league/badge/u2i4uj1615492542.png" },
      { id: "5155", name: "Estonian Hokiliiga", displayName: "Estonian Hokiliiga", badge: "https://r2.thesportsdb.com/images/media/league/badge/j5wd0f1644534883.png" },
      { id: "5156", name: "Hungarian Erste Liga", displayName: "Hungarian Erste Liga", badge: "https://r2.thesportsdb.com/images/media/league/badge/jew79k1644534948.png" },
      { id: "4381", name: "UK Elite Ice Hockey League", displayName: "UK Elite Ice Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/b3ohv51743268423.png" },
      { id: "5601", name: "British NIHL", displayName: "British NIHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/hisiuz1746387408.png" },
      { id: "5068", name: "New Zealand Ice Hockey League", displayName: "New Zealand Ice Hockey Le...", badge: "https://r2.thesportsdb.com/images/media/league/badge/22ye9z1625238990.png" },
      { id: "5277", name: "Champions Hockey League", displayName: "Champions Hockey League", badge: "https://r2.thesportsdb.com/images/media/league/badge/g8srq11650475505.png" },
      { id: "5276", name: "CEHL", displayName: "CEHL", badge: "https://r2.thesportsdb.com/images/media/league/badge/tkcl4v1747747775.png" },
      { id: "5152", name: "Ice Hockey All-Star Games", displayName: "Ice Hockey All-Star Games", badge: "https://r2.thesportsdb.com/images/media/league/badge/qc1i891711811691.png" },
      { id: "5496", name: "NHL 4 Nations", displayName: "NHL 4 Nations", badge: "https://r2.thesportsdb.com/images/media/league/badge/qea4ae1721543049.png" },
      { id: "4976", name: "Mens Ice Hockey World Championships", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/5slhn51739879207.png" },
      { id: "5467", name: "Mens Ice Hockey World Championships Division IA", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/c1mgac1739891091.png" },
      { id: "5468", name: "Mens Ice Hockey World Championships Division IB", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/gwv94k1739898305.png" },
      { id: "5469", name: "Mens Ice Hockey World Championships Division IIA", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/tocyea1744804432.png" },
      { id: "5470", name: "Mens Ice Hockey World Championships Division IIB", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/13txgx1744804463.png" },
      { id: "5471", name: "Mens Ice Hockey World Championships Division IIIA", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/heyok61744804637.png" },
      { id: "5472", name: "Mens Ice Hockey World Championships Division IIIB", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/s6lt531744804692.png" },
      { id: "5473", name: "Mens Ice Hockey World Championships Division IV", displayName: "Mens Ice Hockey World Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/kenn3b1744803948.png" },
      { id: "5137", name: "Olympics Ice Hockey", displayName: "Olympics Ice Hockey", badge: "https://r2.thesportsdb.com/images/media/league/badge/fyvcq71643997533.png" },
      { id: "5376", name: "International Friendlies Ice Hockey", displayName: "International Friendlies ...", badge: "https://r2.thesportsdb.com/images/media/league/badge/slwnr31706859338.png" },
      { id: "5510", name: "Canada Cup", displayName: "Canada Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/a3zec71731419875.png" },
      { id: "5511", name: "Summit Series", displayName: "Summit Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/ckiud41730241024.png" },
      { id: "4810", name: "_Defunct Ice Hockey Teams", displayName: "_Defunct Ice Hockey Teams", badge: "https://r2.thesportsdb.com/images/media/league/badge/64k1621648188802.png" },
      { id: "4838", name: "_No League Ice Hockey", displayName: "_No League Ice Hockey", badge: "https://r2.thesportsdb.com/images/media/league/badge/xxwwwt1421422891.png" },
    ],
  },
  {
    id: "motorsport",
    name: "Motorsport",
    iconName: "motorsport",
    iconType: "svg",
    leagues: [
      { id: "4370", name: "Formula 1", displayName: "F1", badge: "https://r2.thesportsdb.com/images/media/league/badge/g8cofl1513623681.png" },
      { id: "4371", name: "Formula E", displayName: "Formula E", badge: "https://r2.thesportsdb.com/images/media/league/badge/v91pho1674317051.png" },
      { id: "4393", name: "NASCAR Cup Series", displayName: "NASCAR", badge: "https://r2.thesportsdb.com/images/media/league/badge/spqryk1581101437.png" },
      { id: "4513", name: "IndyCar Series", displayName: "IndyCar", badge: "https://r2.thesportsdb.com/images/media/league/badge/7i7e711730372848.png" },
      { id: "4522", name: "MotoGP", displayName: "MotoGP", badge: "https://r2.thesportsdb.com/images/media/league/badge/wthyyx1550753876.png" },
      { id: "4527", name: "World Rally Championship", displayName: "WRC", badge: "https://r2.thesportsdb.com/images/media/league/badge/8ynsy11550754081.png" },
      { id: "4562", name: "Superbike World Championship", displayName: "WSBK", badge: "https://r2.thesportsdb.com/images/media/league/badge/3whbbb1554403060.png" },
      { id: "4796", name: "DTM", displayName: "DTM", badge: "https://r2.thesportsdb.com/images/media/league/badge/uqz8pz1575823050.png" },
    ],
  },
  {
    id: "fighting",
    name: "Fighting",
    iconName: "fighting",
    iconType: "svg",
    leagues: [
      { id: "4443", name: "UFC", displayName: "UFC", badge: "https://r2.thesportsdb.com/images/media/league/badge/bewnz31717531281.png" },
      { id: "4444", name: "WWE", displayName: "WWE", badge: "https://r2.thesportsdb.com/images/media/league/badge/ywtxyv1453504109.png" },
      { id: "4445", name: "Boxing", displayName: "Boxing", badge: "https://r2.thesportsdb.com/images/media/league/badge/6enin21740228549.png" },
      { id: "4448", name: "ROH", displayName: "ROH", badge: "https://r2.thesportsdb.com/images/media/league/badge/57rupq1724308839.png" },
      { id: "4449", name: "NJPW", displayName: "NJPW", badge: "https://r2.thesportsdb.com/images/media/league/badge/yupupv1454525139.png" },
      { id: "4450", name: "WCW", displayName: "WCW", badge: "https://r2.thesportsdb.com/images/media/league/badge/sqyqty1454525104.png" },
      { id: "4451", name: "ECW", displayName: "ECW", badge: "https://r2.thesportsdb.com/images/media/league/badge/wytuuu1454525124.png" },
      { id: "4453", name: "NWA", displayName: "NWA", badge: "https://r2.thesportsdb.com/images/media/league/badge/cb381r1575558932.png" },
      { id: "4455", name: "TNA Wrestling", displayName: "TNA Wrestling", badge: "https://r2.thesportsdb.com/images/media/league/badge/rc6r6l1743067823.png" },
      { id: "4467", name: "Bellator", displayName: "Bellator", badge: "https://r2.thesportsdb.com/images/media/league/badge/jky7bu1534579838.png" },
      { id: "4491", name: "Rizin FF", displayName: "Rizin FF", badge: "https://r2.thesportsdb.com/images/media/league/badge/61lgwt1594731160.png" },
      { id: "4492", name: "Cage Warriors", displayName: "Cage Warriors", badge: "https://r2.thesportsdb.com/images/media/league/badge/nkfxz41545411109.png" },
      { id: "4493", name: "Invicta FC", displayName: "Invicta FC", badge: "https://r2.thesportsdb.com/images/media/league/badge/qitw3r1706290392.png" },
      { id: "4494", name: "ACA", displayName: "ACA", badge: "https://r2.thesportsdb.com/images/media/league/badge/09oc0v1545411656.png" },
      { id: "4495", name: "ONE", displayName: "ONE", badge: "https://r2.thesportsdb.com/images/media/league/badge/lk795c1545411843.png" },
      { id: "4563", name: "AEW", displayName: "AEW", badge: "https://r2.thesportsdb.com/images/media/league/badge/zb3zn01708517335.png" },
      { id: "4567", name: "BKFC", displayName: "BKFC", badge: "https://r2.thesportsdb.com/images/media/league/badge/7pngwh1564344078.png" },
      { id: "4593", name: "AAA", displayName: "AAA", badge: "https://r2.thesportsdb.com/images/media/league/badge/4iokjo1575806386.png" },
      { id: "4594", name: "AJPW", displayName: "AJPW", badge: "https://r2.thesportsdb.com/images/media/league/badge/j9agdp1575808865.png" },
      { id: "4595", name: "CMLL", displayName: "CMLL", badge: "https://r2.thesportsdb.com/images/media/league/badge/8wi2qv1575807644.png" },
      { id: "4596", name: "NOAH", displayName: "NOAH", badge: "https://r2.thesportsdb.com/images/media/league/badge/z7v92q1615058617.png" },
      { id: "4597", name: "UWF", displayName: "UWF", badge: "https://r2.thesportsdb.com/images/media/league/badge/acxdfm1578099434.png" },
      { id: "4598", name: "UWF-i", displayName: "UWF-i", badge: "https://r2.thesportsdb.com/images/media/league/badge/wup7eu1578715393.png" },
      { id: "4599", name: "RINGS", displayName: "RINGS", badge: "https://r2.thesportsdb.com/images/media/league/badge/d3a9ve1578703120.png" },
      { id: "4600", name: "Pancrase", displayName: "Pancrase", badge: "https://r2.thesportsdb.com/images/media/league/badge/bd2duk1578036273.png" },
      { id: "4601", name: "DREAM", displayName: "DREAM", badge: "https://r2.thesportsdb.com/images/media/league/badge/jls5mr1680031432.png" },
      { id: "4602", name: "DEEP", displayName: "DEEP", badge: "https://r2.thesportsdb.com/images/media/league/badge/dan2qk1578034697.png" },
      { id: "4603", name: "IGF", displayName: "IGF", badge: "https://r2.thesportsdb.com/images/media/league/badge/65bjd11578965818.png" },
      { id: "4604", name: "Jungle Fight", displayName: "Jungle Fight", badge: "https://r2.thesportsdb.com/images/media/league/badge/x9cxmq1578222615.png" },
      { id: "4605", name: "K-1", displayName: "K-1", badge: "https://r2.thesportsdb.com/images/media/league/badge/hqik7m1579486345.png" },
      { id: "4608", name: "Battlarts", displayName: "Battlarts", badge: "https://r2.thesportsdb.com/images/media/league/badge/qzyto01578035796.png" },
      { id: "4609", name: "BJW", displayName: "BJW", badge: "https://r2.thesportsdb.com/images/media/league/badge/1li6kw1578035824.png" },
      { id: "4610", name: "BML", displayName: "BML", badge: "https://r2.thesportsdb.com/images/media/league/badge/5e80fs1578034676.png" },
      { id: "4611", name: "GCW", displayName: "GCW", badge: "https://r2.thesportsdb.com/images/media/league/badge/8gwoti1578035868.png" },
      { id: "4612", name: "HUSTLE", displayName: "HUSTLE", badge: "https://r2.thesportsdb.com/images/media/league/badge/8zkoy31578035854.png" },
      { id: "4613", name: "PWFG", displayName: "PWFG", badge: "https://r2.thesportsdb.com/images/media/league/badge/k6djnf1578035710.png" },
      { id: "4614", name: "ZERO-1", displayName: "ZERO-1", badge: "https://r2.thesportsdb.com/images/media/league/badge/17vpr81578890007.png" },
      { id: "4696", name: "Pride FC", displayName: "Pride FC", badge: "https://r2.thesportsdb.com/images/media/league/badge/xw1zad1579739330.png" },
      { id: "4697", name: "FREEDOMS", displayName: "FREEDOMS", badge: "https://r2.thesportsdb.com/images/media/league/badge/c7bvz81650563216.png" },
      { id: "4698", name: "UFO", displayName: "UFO", badge: "https://r2.thesportsdb.com/images/media/league/badge/4hi8xp1579783311.png" },
      { id: "4699", name: "VTJ", displayName: "VTJ", badge: "https://r2.thesportsdb.com/images/media/league/badge/6entwb1579740254.png" },
      { id: "4700", name: "World Japan", displayName: "World Japan", badge: "https://r2.thesportsdb.com/images/media/league/badge/u1h3r51637230285.png" },
      { id: "4701", name: "U-STYLE", displayName: "U-STYLE", badge: "https://r2.thesportsdb.com/images/media/league/badge/covi6a1579775326.png" },
      { id: "4702", name: "WAR", displayName: "WAR", badge: "https://r2.thesportsdb.com/images/media/league/badge/zec3211579787070.png" },
      { id: "4703", name: "Michinoku Pro", displayName: "Michinoku Pro", badge: "https://r2.thesportsdb.com/images/media/league/badge/c5ksff1580189194.png" },
      { id: "4704", name: "KINGDOM", displayName: "KINGDOM", badge: "https://r2.thesportsdb.com/images/media/league/badge/f968l21593347418.png" },
      { id: "4705", name: "AJW", displayName: "AJW", badge: "https://r2.thesportsdb.com/images/media/league/badge/d8pykx1579740243.png" },
      { id: "4706", name: "W-1", displayName: "W-1", badge: "https://r2.thesportsdb.com/images/media/league/badge/n7l2051579741306.png" },
      { id: "4708", name: "Zona 23", displayName: "Zona 23", badge: "https://r2.thesportsdb.com/images/media/league/badge/onas4n1580180870.png" },
      { id: "4709", name: "KSW", displayName: "KSW", badge: "https://r2.thesportsdb.com/images/media/league/badge/7oar5t1580181165.png" },
    ],
  },
  {
    id: "volleyball",
    name: "Volleyball",
    iconName: "volleyball",
    iconType: "svg",
    leagues: [
      { id: "5616", name: "CEV Champions League", displayName: "CEV CL", badge: "https://r2.thesportsdb.com/images/media/league/badge/4etf981746458741.png" },
      { id: "5615", name: "CEV Cup", displayName: "CEV Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/kth50i1746459203.png" },
      { id: "5191", name: "CEV Challenge Cup", displayName: "CEV Challenge", badge: "https://r2.thesportsdb.com/images/media/league/badge/p9vz6p1643464743.png" },
      { id: "4544", name: "Italian Volleyball League", displayName: "Italian M", badge: "https://r2.thesportsdb.com/images/media/league/badge/2y60p61549903109.png" },
      { id: "5186", name: "Italian Womens Volleyball League", displayName: "Italian W", badge: "https://r2.thesportsdb.com/images/media/league/badge/fqo7yj1643379029.png" },
      { id: "4542", name: "Polish PlusLiga", displayName: "Polish PlusLiga", badge: "https://r2.thesportsdb.com/images/media/league/badge/wrwwtr1549902758.png" },
      { id: "4545", name: "Russian Volleyball Super League", displayName: "Russian VL", badge: "https://r2.thesportsdb.com/images/media/league/badge/rxovyl1549903153.png" },
      { id: "4543", name: "Turkish Volleyball League", displayName: "Turkish VL", badge: "https://r2.thesportsdb.com/images/media/league/badge/k0gajr1549902803.png" },
      { id: "4854", name: "German 1. Bundesliga", displayName: "German BL", badge: "https://r2.thesportsdb.com/images/media/league/badge/wkj94n1599575506.png" },
      { id: "5185", name: "French Ligue A Mens Volleyball", displayName: "French M", badge: "https://r2.thesportsdb.com/images/media/league/badge/jmw5hd1643379171.png" },
      { id: "5188", name: "French Ligue A Womens Volleyball", displayName: "French W", badge: "https://r2.thesportsdb.com/images/media/league/badge/o7s9md1643379197.png" },
      { id: "5187", name: "Greek A1 Ethniki", displayName: "Greek A1", badge: "https://r2.thesportsdb.com/images/media/league/badge/1yxq8w1643379211.png" },
      { id: "5189", name: "Volleyliga Belgium", displayName: "Belgian VL", badge: "https://r2.thesportsdb.com/images/media/league/badge/j67v7n1643379328.png" },
      { id: "5083", name: "FIVB Volleyball Mens Nations League", displayName: "FIVB M Nations", badge: "https://r2.thesportsdb.com/images/media/league/badge/vy2eo01625239301.png" },
      { id: "5084", name: "FIVB Volleyball Womens Nations League", displayName: "FIVB W Nations", badge: "https://r2.thesportsdb.com/images/media/league/badge/fkxsyj1685092712.png" },
      { id: "5344", name: "Mens World Volleyball Championship", displayName: "World M", badge: "https://r2.thesportsdb.com/images/media/league/badge/pqfnvg1655390408.png" },
      { id: "5345", name: "Womens World Volleyball Championship", displayName: "World W", badge: "https://r2.thesportsdb.com/images/media/league/badge/bnkh2y1689803190.png" },
      { id: "5184", name: "Mens European Volleyball Championship", displayName: "Euro M", badge: "https://r2.thesportsdb.com/images/media/league/badge/a2vcjy1643379127.png" },
      { id: "5612", name: "Womens European Volleyball Championship", displayName: "Euro W", badge: "https://r2.thesportsdb.com/images/media/league/badge/x5390r1748597766.png" },
      { id: "5048", name: "Olympics Volleyball", displayName: "Olympics M", badge: "https://r2.thesportsdb.com/images/media/league/badge/xuxf3y1687510675.png" },
      { id: "5473", name: "Olympics Volleyball Women", displayName: "Olympics W", badge: "https://r2.thesportsdb.com/images/media/league/badge/xuxf3y1687510675.png" },
      { id: "5047", name: "Olympics Beach Volleyball", displayName: "Beach Olympics", badge: "https://r2.thesportsdb.com/images/media/league/badge/jsnlbx1687510719.png" },
      { id: "5368", name: "Commonwealth Games Beach Volleyball", displayName: "CG Beach", badge: "https://r2.thesportsdb.com/images/media/league/badge/3c9k731684589110.png" },
      { id: "5608", name: "Womens Challenger Cup", displayName: "W Challenger", badge: "https://r2.thesportsdb.com/images/media/league/badge/jzf3x81746189742.png" },
      { id: "5609", name: "Mens Challenger Cup", displayName: "M Challenger", badge: "https://r2.thesportsdb.com/images/media/league/badge/j058vj1746433009.png" },
    ],
  },
  {
    id: "darts",
    name: "Darts",
    iconName: "darts",
    iconType: "svg",
    leagues: [
      { id: "4554", name: "PDC Darts", displayName: "PDC", badge: "https://r2.thesportsdb.com/images/media/league/badge/isf07m1555602216.png" },
      { id: "4561", name: "BDO Darts", displayName: "BDO", badge: "https://r2.thesportsdb.com/images/media/league/badge/bhq78q1555602697.png" },
      { id: "4871", name: "PDC World Darts Championship", displayName: "PDC World", badge: "https://r2.thesportsdb.com/images/media/league/badge/qxd16j1601110974.png" },
    ],
  },
  {
    id: "badminton",
    name: "Badminton",
    iconName: "badminton",
    iconType: "svg",
    leagues: [
      { id: "4758", name: "BWF World Championships", displayName: "BWF Worlds", badge: "https://r2.thesportsdb.com/images/media/league/badge/yrvxrv1570453688.png" },
      { id: "4759", name: "BWF World Tour Finals", displayName: "BWF Finals", badge: "https://r2.thesportsdb.com/images/media/league/badge/xttsuw1570453826.png" },
      { id: "4760", name: "All England Open", displayName: "All England", badge: "https://r2.thesportsdb.com/images/media/league/badge/ytwutv1570453960.png" },
    ],
  },
  {
    id: "table-tennis",
    name: "Table Tennis",
    iconName: "table-tennis",
    iconType: "svg",
    leagues: [
      { id: "5003", name: "Olympics Table Tennis", displayName: "Olympics Table Tennis", badge: "https://r2.thesportsdb.com/images/media/league/badge/9nt4zm1687509732.png" },
      { id: "5371", name: "Commonwealth Games Table Tennis", displayName: "Commonwealth Games Table...", badge: "https://r2.thesportsdb.com/images/media/league/badge/3x66p31733649093.png" },
      { id: "5641", name: "World Table Tennis", displayName: "World Table Tennis", badge: "https://r2.thesportsdb.com/images/media/league/badge/w5o0ic1750443084.png" },
    ],
  },
  {
    id: "golf",
    name: "Golf",
    iconName: "golf",
    iconType: "svg",
    leagues: [
      { id: "5591", name: "_Defunct Golf Teams", displayName: "_Defunct Golf Teams", badge: "https://r2.thesportsdb.com/images/media/league/badge/7ulzaa1741175564.png" },
      { id: "4775", name: "All Thailand Golf Tour", displayName: "All Thailand Golf Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/f9rktl1582573443.png" },
      { id: "4768", name: "Alps Tour", displayName: "Alps Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/ps4sf31582545080.png" },
      { id: "4767", name: "Asian Development Tour", displayName: "Asian Development Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/p21gv61582573543.png" },
      { id: "4762", name: "Asian Tour", displayName: "Asian Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/durtwn1582545153.png" },
      { id: "4773", name: "Big Easy Tour", displayName: "Big Easy Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/2cdf6q1591957229.png" },
      { id: "5557", name: "China Tour", displayName: "China Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/7fencl1736950518.png" },
      { id: "4758", name: "European Challenge Tour", displayName: "European Challenge Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/cjk0ll1590135343.png" },
      { id: "4426", name: "European Tour", displayName: "European Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/mt8ajv1666867699.png" },
      { id: "4777", name: "Japan Challenge Tour", displayName: "Japan Challenge Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/w881zn1592567918.png" },
      { id: "4760", name: "Japan Golf Tour", displayName: "Japan Golf Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/0hzjca1582545594.png" },
      { id: "4766", name: "Korean Tour", displayName: "Korean Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/lf171y1591956671.png" },
      { id: "4763", name: "Korn Ferry Tour", displayName: "Korn Ferry Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/7bagvc1591956878.png" },
      { id: "5438", name: "Ladies European Tour", displayName: "Ladies European Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/c0koh71744396051.png" },
      { id: "5329", name: "LIV Golf", displayName: "LIV Golf", badge: "https://r2.thesportsdb.com/images/media/league/badge/x8p62j1659513228.png" },
      { id: "4553", name: "LPGA Tour", displayName: "LPGA Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/hdnc211555580691.png" },
      { id: "4772", name: "MENA Golf Tour", displayName: "MENA Golf Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/q03e1b1591956701.png" },
      { id: "4769", name: "Nordic Golf League", displayName: "Nordic Golf League", badge: "https://r2.thesportsdb.com/images/media/league/badge/bafz001591957874.png" },
      { id: "5032", name: "Olympics Golf", displayName: "Olympics Golf", badge: "https://r2.thesportsdb.com/images/media/league/badge/g7vr8n1687510131.png" },
      { id: "4770", name: "PGA EuroPro Tour", displayName: "PGA EuroPro Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/y9a2k81591956925.png" },
      { id: "4425", name: "PGA Tour", displayName: "PGA Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/quvqqr1423564787.png" },
      { id: "5556", name: "PGA Tour Americas", displayName: "PGA Tour Americas", badge: "https://r2.thesportsdb.com/images/media/league/badge/xh3xzw1736948162.png" },
      { id: "4765", name: "PGA Tour Canada", displayName: "PGA Tour Canada", badge: "https://r2.thesportsdb.com/images/media/league/badge/svi7or1591957313.png" },
      { id: "4864", name: "PGA Tour Champions", displayName: "PGA Tour Champions", badge: "https://r2.thesportsdb.com/images/media/league/badge/s4xljf1600855962.png" },
      { id: "4774", name: "PGA Tour China", displayName: "PGA Tour China", badge: "https://r2.thesportsdb.com/images/media/league/badge/cdim7h1592391134.png" },
      { id: "4764", name: "PGA Tour Latinoamérica", displayName: "PGA Tour Latinoamérica", badge: "https://r2.thesportsdb.com/images/media/league/badge/h7zojf1591957352.png" },
      { id: "4761", name: "PGA Tour of Australasia", displayName: "PGA Tour of Australasia", badge: "https://r2.thesportsdb.com/images/media/league/badge/ce5bzs1751484107.png" },
      { id: "4776", name: "Professional Golf Tour of India", displayName: "Professional Golf Tour of...", badge: "https://r2.thesportsdb.com/images/media/league/badge/lz6eiv1592391649.png" },
      { id: "4771", name: "ProGolf Tour", displayName: "ProGolf Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/pqhtf51592391957.png" },
      { id: "4740", name: "South African Sunshine Tour", displayName: "South African Sunshine Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/s4bq4z1582232923.png" },
    ],
  },
  {
    id: "rugby",
    name: "Rugby",
    iconName: "rugby",
    iconType: "svg",
    leagues: [
      { id: "5562", name: "_Defunct Rugby Teams", displayName: "_Defunct Rugby Teams", badge: "https://r2.thesportsdb.com/images/media/league/badge/x6liv41738949510.png" },
      { id: "5447", name: "_No League Rugby", displayName: "_No League Rugby", badge: "https://r2.thesportsdb.com/images/media/league/badge/ra0fks1738949662.png" },
      { id: "4417", name: "Australian National Rugby Championship", displayName: "Australian National Rugby...", badge: "https://r2.thesportsdb.com/images/media/league/badge/kb89dn1535795440.png" },
      { id: "4416", name: "Australian National Rugby League", displayName: "Australian National Rugby...", badge: "https://r2.thesportsdb.com/images/media/league/badge/gsztcj1552071996.png" },
      { id: "5171", name: "Australian Shute Shield", displayName: "Australian Shute Shield", badge: "https://r2.thesportsdb.com/images/media/league/badge/39u4ad1716376979.png" },
      { id: "4984", name: "Autumn Nations Cup", displayName: "Autumn Nations Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/wvlly21623937678.png" },
      { id: "5512", name: "British and Irish Lions Tours", displayName: "British and Irish Lions T...", badge: "https://r2.thesportsdb.com/images/media/league/badge/iob1un1737973257.png" },
      { id: "5370", name: "Commonwealth Games 7s Rugby", displayName: "Commonwealth Games 7s Rugby", badge: "https://r2.thesportsdb.com/images/media/league/badge/sjo2k31679328973.png" },
      { id: "5069", name: "Currie Cup", displayName: "Currie Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/4t35id1720081373.png" },
      { id: "4414", name: "English Prem Rugby", displayName: "English Prem Rugby", badge: "https://r2.thesportsdb.com/images/media/league/badge/r59qxy1755025703.png" },
      { id: "5695", name: "English Prem Rugby Cup", displayName: "English Prem Rugby Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/lu77yo1757673369.png" },
      { id: "5166", name: "English Premier 15s", displayName: "English Premier 15s", badge: "https://r2.thesportsdb.com/images/media/league/badge/g0w1oc1757145719.png" },
      { id: "4589", name: "English RFL Championship", displayName: "English RFL Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/em9mfx1575052342.png" },
      { id: "4722", name: "English RFU Championship", displayName: "English RFU Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/aym81n1738865698.png" },
      { id: "4415", name: "English Rugby League Super League", displayName: "English Rugby League Supe...", badge: "https://r2.thesportsdb.com/images/media/league/badge/gp2sfv1641835011.png" },
      { id: "5418", name: "European Rugby Challenge Cup", displayName: "European Rugby Challenge Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/ewua6c1716755405.png" },
      { id: "4550", name: "European Rugby Champions Cup", displayName: "European Rugby Champions Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/kohne11716546580.png" },
      { id: "5558", name: "French Nationale", displayName: "French Nationale", badge: "https://r2.thesportsdb.com/images/media/league/badge/vqd4a01738835656.png" },
      { id: "5172", name: "French Pro D2", displayName: "French Pro D2", badge: "https://r2.thesportsdb.com/images/media/league/badge/ng4ixj1645178002.png" },
      { id: "4430", name: "French Top 14", displayName: "French Top 14", badge: "https://r2.thesportsdb.com/images/media/league/badge/xrsqtw1452903237.png" },
      { id: "5167", name: "Japan Rugby League One", displayName: "Japan Rugby League One", badge: "https://r2.thesportsdb.com/images/media/league/badge/pycpdk1717092494.png" },
      { id: "5559", name: "Japanese League One D2", displayName: "Japanese League One D2", badge: "https://r2.thesportsdb.com/images/media/league/badge/sc4ohu1738836388.png" },
      { id: "5560", name: "Japanese League One D3", displayName: "Japanese League One D3", badge: "https://r2.thesportsdb.com/images/media/league/badge/5hiali1738836432.png" },
      { id: "5070", name: "Major League Rugby", displayName: "Major League Rugby", badge: "https://r2.thesportsdb.com/images/media/league/badge/ofaqx01625360658.png" },
      { id: "5278", name: "New Zealand National Provincial Championship", displayName: "New Zealand National Prov...", badge: "https://r2.thesportsdb.com/images/media/league/badge/kpcsv71650475606.png" },
      { id: "4981", name: "North American Rugby League", displayName: "North American Rugby League", badge: "https://r2.thesportsdb.com/images/media/league/badge/llw4et1623950988.png" },
      { id: "5037", name: "Olympics 7s Rugby", displayName: "Olympics 7s Rugby", badge: "https://r2.thesportsdb.com/images/media/league/badge/gi66pe1687510165.png" },
      { id: "4985", name: "Pacific Nations Cup", displayName: "Pacific Nations Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/egbkvq1716567039.png" },
      { id: "5168", name: "Romanian SuperLiga", displayName: "Romanian SuperLiga", badge: "https://r2.thesportsdb.com/images/media/league/badge/9nhuo61738949987.png" },
      { id: "4986", name: "Rugby Championship", displayName: "Rugby Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/dy0n4c1716684531.png" },
      { id: "4983", name: "Rugby Europe Championship", displayName: "Rugby Europe Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/c9zh921716559969.png" },
      { id: "5480", name: "Rugby Union Club Friendlies", displayName: "Rugby Union Club Friendlies", badge: "https://r2.thesportsdb.com/images/media/league/badge/8wdikp1738946921.png" },
      { id: "5479", name: "Rugby Union International Friendlies", displayName: "Rugby Union International...", badge: "https://r2.thesportsdb.com/images/media/league/badge/wvurc21720171967.png" },
      { id: "4574", name: "Rugby World Cup", displayName: "Rugby World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/ehulf71716558271.png" },
      { id: "5173", name: "Scottish Premiership", displayName: "Scottish Premiership", badge: "https://r2.thesportsdb.com/images/media/league/badge/g8ojwl1646332780.png" },
      { id: "4714", name: "Six Nations Championship", displayName: "Six Nations Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/7h1wr91738670253.png" },
      { id: "5082", name: "Six Nations Under 20s Championship", displayName: "Six Nations Under 20s Cha...", badge: "https://r2.thesportsdb.com/images/media/league/badge/mngoos1756567984.png" },
      { id: "5563", name: "Six Nations Women", displayName: "Six Nations Women", badge: "https://r2.thesportsdb.com/images/media/league/badge/taxsol1739096406.png" },
      { id: "5170", name: "Spanish División de Honor", displayName: "Spanish División de Honor", badge: "https://r2.thesportsdb.com/images/media/league/badge/fe42a11716909078.png" },
      { id: "5169", name: "Super Liga Americana", displayName: "Super Liga Americana", badge: "https://r2.thesportsdb.com/images/media/league/badge/gz76vv1717091774.png" },
      { id: "4551", name: "Super Rugby", displayName: "Super Rugby", badge: "https://r2.thesportsdb.com/images/media/league/badge/alpxhe1675871443.png" },
      { id: "5701", name: "Super Rugby Aus", displayName: "Super Rugby Aus", badge: "https://www.thesportsdb.com/images/media/league/badge/b9v2541758885749.png" },
      { id: "4446", name: "United Rugby Championship", displayName: "United Rugby Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/o6dhfo1716481482.png" },
      { id: "5165", name: "URBA Top 13", displayName: "URBA Top 13", badge: "https://r2.thesportsdb.com/images/media/league/badge/cq1azd1716915260.png" },
      { id: "5682", name: "Womens Rugby World Cup", displayName: "Womens Rugby World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/vphokh1755422562.png" },
    ],
  },
  {
    id: "tennis",
    name: "Tennis",
    iconName: "tennis",
    iconType: "svg",
    leagues: [
      { id: "4464", name: "ATP World Tour", displayName: "ATP World Tour", badge: "https://r2.thesportsdb.com/images/media/team/badge/cav6c81546113141.png" },
      { id: "4422", name: "ITF Womens World Tennis Tour", displayName: "ITF Womens", badge: "https://r2.thesportsdb.com/images/media/league/badge/l3jovw1516960585.png" },
      { id: "5379", name: "Olympics Tennis", displayName: "Olympics Tennis", badge: "https://r2.thesportsdb.com/images/media/league/badge/uhtq8b1687510195.png" },
      { id: "5378", name: "Tennis ATP Challenger Tour", displayName: "Tennis ATP Challenger Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/gzfnxc1683898054.png" },
      { id: "5526", name: "Tennis Next Gen ATP Finals", displayName: "Tennis Next Gen ATP Finals", badge: "https://r2.thesportsdb.com/images/media/league/badge/xt5swg1731682034.png" },
      { id: "4421", name: "WTA Tour", displayName: "WTA Tour", badge: "https://r2.thesportsdb.com/images/media/league/badge/qgvsmy1753208524.png" },
    ],
  },
  {
    id: "cricket",
    name: "Cricket",
    iconName: "cricket",
    iconType: "svg",
    leagues: [
      { id: "4808", name: "_Defunct Cricket Teams", displayName: "_Defunct Cricket Teams", badge: "https://r2.thesportsdb.com/images/media/league/badge/s2trsa1589493223.png" },
      { id: "4841", name: "_No League Cricket", displayName: "_No League Cricket", badge: "https://r2.thesportsdb.com/images/media/league/badge/xxwwwt1421422891.png" },
      { id: "4461", name: "Australian Big Bash League", displayName: "Australian Big Bash League", badge: "https://r2.thesportsdb.com/images/media/league/badge/yko7ny1546635346.png" },
      { id: "5529", name: "Bangladesh Premier League", displayName: "Bangladesh Premier League", badge: "https://r2.thesportsdb.com/images/media/league/badge/3smqzk1734192770.png" },
      { id: "5176", name: "Caribbean Premier League", displayName: "Caribbean Premier League", badge: "https://r2.thesportsdb.com/images/media/league/badge/5mjjnj1645179844.png" },
      { id: "5361", name: "Commonwealth Games Cricket", displayName: "Commonwealth Games Cricket", badge: "https://r2.thesportsdb.com/images/media/league/badge/g0j9r71677837152.png" },
      { id: "5606", name: "Cricket Ireland Inter-Provincial T20 Trophy", displayName: "Cricket Ireland Inter-Pro...", badge: "https://r2.thesportsdb.com/images/media/league/badge/mca6gl1746348043.png" },
      { id: "4575", name: "Cricket World Cup", displayName: "Cricket World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/kla0wp1689752873.png" },
      { id: "4458", name: "English County Championship Division 1", displayName: "English County Championsh...", badge: "https://r2.thesportsdb.com/images/media/league/badge/d4q9uf1630694697.png" },
      { id: "4459", name: "English County Championship Division 2", displayName: "English County Championsh...", badge: "https://r2.thesportsdb.com/images/media/league/badge/xedhy31487332623.png" },
      { id: "4463", name: "English t20 Blast", displayName: "English t20 Blast", badge: "https://r2.thesportsdb.com/images/media/league/badge/m1lsns1649766933.png" },
      { id: "5531", name: "Global Super League", displayName: "Global Super League", badge: "https://r2.thesportsdb.com/images/media/league/badge/e34ujo1742154629.png" },
      { id: "5587", name: "ICC Champions Trophy", displayName: "ICC Champions Trophy", badge: "https://r2.thesportsdb.com/images/media/league/badge/r7gr431740091965.png" },
      { id: "5103", name: "ICC Mens T20 World Cup", displayName: "ICC Mens T20 World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/jc2g4c1651173316.png" },
      { id: "5104", name: "ICC Womens T20 World Cup", displayName: "ICC Womens T20 World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/bh1gnu1727900778.png" },
      { id: "5100", name: "ICC World Test Championship", displayName: "ICC World Test Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/ejkl931662127133.png" },
      { id: "4460", name: "Indian Premier League", displayName: "Indian Premier League", badge: "https://r2.thesportsdb.com/images/media/league/badge/gaiti11741709844.png" },
      { id: "5490", name: "International League T20", displayName: "International League T20", badge: "https://r2.thesportsdb.com/images/media/league/badge/omdaqg1721481629.png" },
      { id: "4844", name: "International Test Match Series", displayName: "International Test Match ...", badge: "https://r2.thesportsdb.com/images/media/league/badge/rh43t11595182229.png" },
      { id: "5175", name: "Lanka Premier League", displayName: "Lanka Premier League", badge: "https://r2.thesportsdb.com/images/media/league/badge/qqhube1720698337.png" },
      { id: "4843", name: "New Zealand Super Smash", displayName: "New Zealand Super Smash", badge: "https://r2.thesportsdb.com/images/media/league/badge/ilj7lz1671798360.png" },
      { id: "5483", name: "Olympics Cricket", displayName: "Olympics Cricket", badge: "https://r2.thesportsdb.com/images/media/league/badge/xrlj5m1720165614.png" },
      { id: "5585", name: "One-Day International Series", displayName: "One-Day International Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/jmz1bw1739463992.png" },
      { id: "5552", name: "Pakistan Super League", displayName: "Pakistan Super League", badge: "https://r2.thesportsdb.com/images/media/league/badge/x0b1wq1733923113.png" },
      { id: "5105", name: "SA20", displayName: "SA20", badge: "https://r2.thesportsdb.com/images/media/league/badge/2kd44m1671799318.png" },
      { id: "4842", name: "South African Mzansi Super League", displayName: "South African Mzansi Supe...", badge: "https://r2.thesportsdb.com/images/media/league/badge/gf42m61541000813.png" },
      { id: "5586", name: "T20 International Series", displayName: "T20 International Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/gnbzme1739464008.png" },
      { id: "5412", name: "The Hundred", displayName: "The Hundred", badge: "https://r2.thesportsdb.com/images/media/league/badge/i3oqw61703006685.png" },
      { id: "5178", name: "Vitality T20 Blast", displayName: "Vitality T20 Blast", badge: "https://r2.thesportsdb.com/images/media/league/badge/m1lsns1649766933.png" },
      { id: "5563", name: "Womens Big Bash League", displayName: "Womens Big Bash League", badge: "https://r2.thesportsdb.com/images/media/league/badge/ejhz0x1738931363.png" },
      { id: "5177", name: "Womens Cricket World Cup", displayName: "Womens Cricket World Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/u3ijt11645179868.png" },
      { id: "5414", name: "Womens Premier League", displayName: "Womens Premier League", badge: "https://r2.thesportsdb.com/images/media/league/badge/fwx83q1703094612.png" },
      { id: "5413", name: "Womens T20 Challenger Trophy", displayName: "Womens T20 Challenger Trophy", badge: "https://r2.thesportsdb.com/images/media/league/badge/r82i351703007188.png" },
      { id: "5179", name: "Zimbabwe T20 Super Cup", displayName: "Zimbabwe T20 Super Cup", badge: "https://r2.thesportsdb.com/images/media/league/badge/kmr9gc1645180127.png" },
    ],
  },
  {
    id: "cs2",
    name: "Counter Strike",
    iconName: "cs2",
    iconType: "custom",
    leagues: [
      { id: "5426", name: "Blast Premier", displayName: "Blast Premier", badge: "https://r2.thesportsdb.com/images/media/league/badge/6cg6vm1748428090.png" },
      { id: "5425", name: "ESL Pro League", displayName: "ESL Pro League", badge: "https://r2.thesportsdb.com/images/media/league/badge/iwnm681705172445.png" },
      { id: "5446", name: "ESL One", displayName: "ESL One", badge: "https://r2.thesportsdb.com/images/media/league/badge/n60j231714400189.png" },
    ],
  },
  {
    id: "dota2",
    name: "Dota 2",
    iconName: "dota2",
    iconType: "custom",
    leagues: [
      { id: "dota2-1", name: "The International", displayName: "The International", badge: "https://liquipedia.net/commons/images/c/c2/The_International_lightmode.png" },
      { id: "dota2-2", name: "Dota Pro Circuit", displayName: "DPC", badge: "https://liquipedia.net/commons/images/5/5c/Dota_Pro_Circuit_2021_lightmode.png" },
      { id: "dota2-3", name: "ESL One Dota 2", displayName: "ESL One", badge: "https://r2.thesportsdb.com/images/media/league/badge/n60j231714400189.png" },
    ],
  },
  {
    id: "lol",
    name: "League of Legends",
    iconName: "lol",
    iconType: "custom",
    leagues: [
      { id: "4514", name: "League of Legends World Championship", displayName: "Worlds", badge: "https://r2.thesportsdb.com/images/media/league/badge/v60b971706041095.png" },
      { id: "4529", name: "League of Legends Champions Korea", displayName: "LCK", badge: "https://r2.thesportsdb.com/images/media/league/badge/llpp2i1705953103.png" },
      { id: "4531", name: "League of Legends Championship Series", displayName: "LCS", badge: "https://r2.thesportsdb.com/images/media/league/badge/nu81po1705482188.png" },
      { id: "4530", name: "League of Legends EMEA Championship", displayName: "LEC", badge: "https://r2.thesportsdb.com/images/media/league/badge/djubyo1705150930.png" },
      { id: "4532", name: "League of Legends Pacific Championship Series", displayName: "PCS", badge: "https://r2.thesportsdb.com/images/media/league/badge/qoa38y1705171719.png" },
      { id: "4528", name: "League of Legends Pro League", displayName: "LPL", badge: "https://r2.thesportsdb.com/images/media/league/badge/fqgzgl1706041210.png" },
      { id: "5631", name: "League of The Americas", displayName: "LTA", badge: "https://r2.thesportsdb.com/images/media/league/badge/uyi96c1748525232.png" },
    ],
  },
  {
    id: "valorant",
    name: "Valorant",
    iconName: "valorant",
    iconType: "custom",
    leagues: [
      { id: "5422", name: "Valorant Champions Tour", displayName: "VCT", badge: "https://r2.thesportsdb.com/images/media/league/badge/ihvdp41748984192.png" },
    ],
  },
  {
    id: "esports",
    name: "ESports",
    iconName: "Gamepad2",
    leagues: [
      { id: "5450", name: "_No League ESports", displayName: "_No League ESports", badge: "https://www.thesportsdb.com/images/media/league/badge/zqrfmt1761256831.png" },
      { id: "5423", name: "Apex Legends Global Series", displayName: "Apex Legends Global Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/658s101705170243.png" },
      { id: "4715", name: "Call of Duty League", displayName: "Call of Duty League", badge: "https://r2.thesportsdb.com/images/media/league/badge/oirs421581113488.png" },
      { id: "4716", name: "Call of Duty World League", displayName: "Call of Duty World League", badge: "https://r2.thesportsdb.com/images/media/league/badge/6onjpj1581118029.png" },
      { id: "4874", name: "eNASCAR iRacing Series", displayName: "eNASCAR iRacing Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/dyiisd1603480217.png" },
      { id: "5427", name: "FC Pro World Championship", displayName: "FC Pro World Championship", badge: "https://r2.thesportsdb.com/images/media/league/badge/5db8qa1705174191.png" },
      { id: "4568", name: "FIFA eWorld Cup Series", displayName: "FIFA eWorld Cup Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/iaff651564824151.png" },
      { id: "4515", name: "Fortnite", displayName: "Fortnite", badge: "https://r2.thesportsdb.com/images/media/league/badge/bdkdn51549463678.png" },
      { id: "5424", name: "Halo Championship Series", displayName: "Halo Championship Series", badge: "https://r2.thesportsdb.com/images/media/league/badge/jzvw631705170844.png" },
      { id: "4717", name: "Overwatch League", displayName: "Overwatch League", badge: "https://r2.thesportsdb.com/images/media/league/badge/7w4mgw1581158134.png" },
      { id: "5421", name: "Rocket League Championship Series", displayName: "Rocket League Championshi...", badge: "https://r2.thesportsdb.com/images/media/league/badge/q9qgwg1705154603.png" },
    ],
  },
];
